# Generated by Django 4.2 on 2023-05-05 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('copo', models.CharField(choices=[(1, 'Primeiro Valor'), (2, 'Segundo Valor')], max_length=8)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ConsumoAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(choices=[(1, 'Primeiro Valor'), (2, 'Segundo Valor')], max_length=8)),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estoque')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
