# Generated by Django 4.2 on 2023-05-05 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_estoque_consumoagua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumoagua',
            name='estoque',
        ),
        migrations.AddField(
            model_name='consumoagua',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='consumoagua',
            name='quantidade',
            field=models.CharField(choices=[(1, '250'), (2, 'Segundo Valor')], max_length=8),
        ),
    ]
