# Generated by Django 4.2 on 2023-05-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_consumoagua_estoque_consumoagua_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumoagua',
            name='quantidade',
            field=models.CharField(choices=[(250, '250'), (350, '350')], max_length=8),
        ),
    ]
