# Generated by Django 4.2 on 2023-05-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_consumoagua_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumoagua',
            name='quantidade',
            field=models.CharField(choices=[(250, 250), (350, 350)], max_length=8),
        ),
    ]
