# Generated by Django 4.2 on 2023-05-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_consumoagua_quantidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumoagua',
            options={},
        ),
        migrations.RemoveField(
            model_name='consumoagua',
            name='data',
        ),
        migrations.RemoveField(
            model_name='consumoagua',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='consumoagua',
            name='copo_escolhido',
            field=models.CharField(choices=[('CP', '250'), ('CG', '450')], default='CP', max_length=2),
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
